# Generated by Django 5.2 on 2025-04-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='event_types',
            field=models.JSONField(default=list),
        ),
    ]
