# Generated by Django 5.2 on 2025-04-26 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_alter_subscription_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
