# Generated by Django 5.2 on 2025-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_alter_webhookdeliverylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
