# Generated by Django 5.2 on 2025-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_alter_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
